lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
title: CSC
description: Clinical Scientific Computing
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-architect
